project_name: nais-salsa

before:
  hooks:
    - go mod tidy

builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    id: nais
    dir: .
    main: ./cmd
    binary: salsa
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

checksum:
  name_template: 'checksums.txt'

archives:
  - format: binary

sboms:
  - artifacts: binary

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: ["sign-blob", "--key=cosign.key", "--output-signature", "${artifact}.sig"]
    artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: allow
  draft: true
  github:
    owner: nais
    name: salsa
  header: |
    ## nais-salsa-cli ({{ .Version }})
  extra_files:
    - glob: "cosign.pub"

#brews:
#  - tap:
#      owner: nais
#      name: homebrew-tap
#      token: "{{ .Env.PUSH_TOKEN }}"
#    name: salsa
#    homepage: "https://github.com/nais/salsa"
#    description: "Command-line interface for SLSA provenance"
#    license: MIT
#    folder: Formula
#    install: |
#      bin.install "salsa"
#    test: |
#      assert_match version, shell_output("#{bin}/salsa version")
#
#nfpms:
#  - package_name: salsa
#    file_name_template: "{{ .PackageName }}_{{ .Version }}"
#    vendor: NAV / nais team
#    homepage: "https://github.com/nais/salsa"
#    maintainer: NAV / nais team
#    description: "Command-line interface for SLSA provenance"
#    license: MIT
#    formats:
#      - deb
#    version_metadata: git