name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:

  repo_dir:
    description: |-
      Internal value (do not set): Root of directory to look for build files.
      Defualts to $GITHUB_WORKSPACE.
    required: false
    default: ${{ github.workspace }}

  repo_sub_dir:
    description: |-
      Specify a sub directory if build file not found in working root directory
    required: false
    default: ""

  repo_name:
    description: |-
      Name of the file and path to provenance.
      Used as an relative path under $GITHUB_WORKSPACE.
      Defaults to "github.repository".
    required: false
    default: ${{ github.repository }}

  key:
    description: |-
      The key used to sign the attestation
    required: true

  image:
    description: |-
      docker image to sign. Defaults to $ENV_IMAGE.
    required: true

  github_context:
    description: |-
      Internal value (do not set): the "github" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(github) }}

  runner_context:
    description: |-
      Internal value (do not set): the "runner" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(runner) }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_dir }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.github_context }}
    - ${{ inputs.runner_context }}
    - ${{ inputs.image }}
    - ${{ inputs.env_context }}
    - ${{ inputs.repo_sub_dir }}
    - ${{ inputs.key }}
