name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:
  repo_dir:
    description: 'path to directory of artifacts'
    required: true
    default: '${{ github.workspace }}'
  repo_name:
    description: 'path to write build provenance file'
    required: true
    default: '${{ github.repository.name }}'
  image:
    description: 'docker image to pull and sign'
    required: true
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  env_context:
    description: 'internal (do not set): the "env" context object in json'
    required: true
    default: ${{ toJSON(env) }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_dir }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.github_context }}
    - ${{ inputs.runner_context }}