name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:

  repo_dir:
    description: |-
      Root of directory to look for build files.
      Defualts to $GITHUB_WORKSPACE.
    required: false
    default: ${{ github.workspace }}

  repo_name:
    description: |-
      Name of the file and path to provenance.
      Used as an relative path under $GITHUB_WORKSPACE.
      Defaults to "github.repository".
    required: false
    default: ${{ github.repository }}

  image:
    description: |-
      docker image to sign
    required: true

  github_context:
    description: |-
      Internal value (do not set): the "github" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(github) }}

  runner_context:
    description: |-
      Internal value (do not set): the "runner" context object in json.
      The context is used when generating provenance.
    required: false
    default: ${{ toJSON(runner) }}

  env_context:
    description: |-
      This information about object "env" must be sent inn. It is not availible from the 
      action.yml. To provide the current job environment varibales, the "env"
      objecct need to be sendt inn.
    required: false
    default: "{}"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_dir }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.github_context }}
    - ${{ inputs.runner_context }}
    - ${{ inputs.image }}
    - ${{ inputs.env_context }}