name: 'NAIS SLSA Provenance Action'
description: 'A POC Action to generate signed SLSA provenance'
branding:
  icon: lock
  color: red
inputs:
  repo_dir:
    description: 'path to directory of artifacts'
    required: true
    default: '.'
  repo_name:
    description: 'path to write build provenance file'
    required: true
    default: '${{ github.repository.name }}.provenance'
  image:
    description: 'docker image to pull and sign'
    required: true
    default: ${{ IMAGE }}
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
  env_context:
    description: 'internal (do not set): the "env" context object in json'
    required: true
    default: ${{ toJSON(env) }}
runs:
  using: 'docker'
  image: 'Dockerfile'