name: golangci-lint
on: [push]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # wait for support go 1.18: https://github.com/golangci/golangci-lint/issues/2649.
      #- name: Extract version of Go to use
      #  run: echo "GOVERSION=$(cat go.mod | grep -w "go" | awk ' { print $2 } ' | grep -w "^[^v]")" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17 #${{ env.GOVERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Wait for action go 1.18 support
          version: v1.44.2 #v1.45.2