name: NAIS SALSA

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/navikt/gandalf/gandalf-security-token-service:90b27f4bb7d23e81b70442c7cfd76090843b68b3

jobs:
  generate-provenance:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate provenance
        uses: nais/salsa@main
        with:
          image: ${{ env.IMAGE }}
          repo_dir: ${{ github.workspace }}/tmp
          repo_name: salsa

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: tmp/salsa.provenance